### ISSUE TITLE
Support for songs using non-latin characters e.g. Russian

### ISSUE THREAD

**Issue by sectune** [Shubhamrawat5/apple-playlist-downloader#2]
Thanks a lot for this script, works like a charm for me! 

Just one issue I have which is easy to reproduce. Try adding a song with a cyrillic title in your playlist and run the script. You'll encounter the following stack as below when the script tries to download the first cyrillic/non-latin song. Would you please be so kind and take a look at it? Would be amazing if this could be fixed! 

Thanks once more, big fan of your work!

internal/process/promises.js:213
        triggerUncaughtException(err, true /* fromPromise */);
        ^

TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:155:13)
    at Object.request (https.js:374:10)
    at RedirectableRequest._performRequest (/Location/apple-playlist-downloader/node_modules/follow-redirects/index.js:241:24)
    at new RedirectableRequest (/Location/apple-playlist-downloader/node_modules/follow-redirects/index.js:60:8)
    at Object.request (/Location/apple-playlist-downloader/node_modules/follow-redirects/index.js:437:14)
    at dispatchHttpRequest (/Location/apple-playlist-downloader/node_modules/axios/lib/adapters/http.js:195:25)
    at new Promise (<anonymous>)
    at httpAdapter (/Location/apple-playlist-downloader/node_modules/axios/lib/adapters/http.js:46:10)
    at dispatchRequest (/Location/apple-playlist-downloader/node_modules/axios/lib/core/dispatchRequest.js:52:10)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: 'ERR_UNESCAPED_CHARACTERS'

**Comment by Shubhamrawat5** [comment]
Yeah thanks. can you post the song full name which caused this problem? Will check

**Comment by sectune** [comment]
The name of the song is: Я не отдам тебя никому from Ruki Vverkh from the Album The Best (Deluxe Version)

Thanks a lot!

**Comment by Shubhamrawat5** [comment]
Hey, It is fixed now i think. Check it by pulling new code i just pushed.

**Comment by sectune** [comment]
wow, that was quick! I did a git clone and cloned in a fresh dir but unfortunately I now encounter an error as soon as I execute:

internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module 'progress'
Require stack:
- /Location/app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Location/app.js:2:19)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Location/app.js'
  ]
}

**Comment by Shubhamrawat5** [comment]
Yeah. I just added a small inbuilt function. "Error: Cannot find module 'progress'" this shows you don't have package installed so run command -> npm install

**Comment by sectune** [comment]
Thank you very much! It worked, stupid me forgot the npm install :) You are amazing if I can chip-in for a beer for you somehow, please let me know!
