### ISSUE TITLE
Cannot read properties of undefined?

### ISSUE THREAD

**Issue by Dibucci** [Shubhamrawat5/apple-playlist-downloader#23]
as the title says i get an error during my download of a Lo-Fi playlist that just says 

TypeError: Cannot read properties of undefined (reading '0')
    at getURL (C:\Users\%UserProfile%\Music\Apple Music\apple-playlist-downloader\app.js:136:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

and this is the playlist I used https://music.apple.com/us/playlist/lofi-hip-hop-music-beats-to-relax-study-to/pl.bf7a3cbca49644d8a33f09c1285aef5c

IK it will only do 100 songs rn but thats besides the point, I've tried to change the url to a diffrent playlist and it gives me the same error message as the one above.

idk if its something i did or not but i followed the instructions to a "T", also I should mention it did download like 20+ songs before it stopped and showed this Error

Oh and before the error popped up, this showed up first

C:\Users\%UserProfile%\Music\Apple Music\apple-playlist-downloader\app.js:136
  if (!data["audios"][""][0].id) {
                         ^
oh and for privacy i changed the User part of the paths to %UserProfile% but in the console it's my actual user profile that shows

**Comment by arvage** [comment]
it is also stopped working for me. 
```
(node:31108) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at getURL (C:\Users\armingorji.kagan\AppleDownloader\apple-playlist-downloader\app.js:136:26)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at emitUnhandledRejectionWarning (internal/process/promises.js:168:15)
    at processPromiseRejections (internal/process/promises.js:247:11)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)
(node:31108) TypeError: Cannot read property '0' of undefined
    at getURL (C:\Users\armingorji.kagan\AppleDownloader\apple-playlist-downloader\app.js:136:26)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:31108) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-z
ero exit code.
    at emitDeprecationWarning (internal/process/promises.js:180:11)
    at processPromiseRejections (internal/process/promises.js:249:13)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)
```

**Comment by slunnnko** [comment]
I did a little debugging and the problem is the site it uses to download the songs https://slider.kz. It is down.

**Comment by Shubhamrawat5** [comment]
Site should be up by now and running
